% addpath([fileparts(mfilename('fullpath')) '\RASPlib'],...
% 		[fileparts(mfilename('fullpath')) '\RASPlib\src'],...
% 		[fileparts(mfilename('fullpath')) '\RASPlib\include'],...
% 		[fileparts(mfilename('fullpath')) '\RASPlib\examples'],...
% 		[fileparts(mfilename('fullpath')) '\RASPlib\blocks'])
   
% clc
addpath('src','include','examples','blocks','Multirate Sampling','BalanceApp')
% cd CompileFolder % move to CompileFolder on start (optional)
